In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("/content/10) DateFruit Dataset.csv")
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [28]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [5]:
x=df.drop("Class",axis=1)
y=df["Class"]

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [ ]:
#ANN

In [9]:
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader

In [10]:
torch.manual_seed(42)
np.random.seed(42)
print("Random seeds set for reproducibility.")

Random seeds set for reproducibility.

With random seeds set, the initial weights of the neural network will be the same every time the code runs, leading to reproducible results for the initial loss. This should help in comparing results with your teacher. Also, ensure the `random_state` in `train_test_split` (currently 42) is consistent.

In [11]:
x_train_tensor=torch.tensor(x_train_scaled,dtype=torch.float32)
y_train_tensor=torch.tensor(y_train,dtype=torch.long)

x_test_tensor=torch.tensor(x_test_scaled,dtype=torch.float32)
y_test_tensor=torch.tensor(y_test,dtype=torch.long)

In [12]:
train_dataset=TensorDataset(x_train_tensor,y_train_tensor)
test_dataset=TensorDataset(x_test_tensor,y_test_tensor)

In [13]:
train_loader=DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=32)

In [14]:
class ANN(nn.Module):
  def __init__(self):
    super(ANN,self).__init__()

    self.model=nn.Sequential(
        #1st Hidden layer
        nn.Linear(x_train.shape[1],64),
        nn.ReLU(),

        #2nd Hidden layer
        nn.Linear(64,64),
        nn.ReLU(),


        #final output layer
        nn.Linear(64,len(np.unique(y_train)))
    )

  def forward(self,x):
    return self.model(x);

In [15]:
model=ANN()

from torch.optim import Adam
criteria=nn.CrossEntropyLoss()
optimizer=Adam(model.parameters())

In [16]:
epochs=100

for epoch in range(epochs):

  model.train() # model enters training mode


  running_loss=0.0
  for xb,yb in train_loader:
    optimizer.zero_grad() # clears gradients
    outputs=model(xb)
    loss=criteria(outputs,yb)
    loss.backward()
    optimizer.step()

    running_loss+=loss.item()

  training_loss=running_loss/len(train_loader)
  print(f"Epoch ${epoch+1}/{epochs} loss : ",training_loss)

Epoch $1/100 loss :  1.7450501866962598
Epoch $2/100 loss :  1.119205803974815
Epoch $3/100 loss :  0.7010098203368809
Epoch $4/100 loss :  0.5306420987067015
Epoch $5/100 loss :  0.45933071297148
Epoch $6/100 loss :  0.3934824777686078
Epoch $7/100 loss :  0.35058385652044544
Epoch $8/100 loss :  0.31356864454953565
Epoch $9/100 loss :  0.2879743271547815
Epoch $10/100 loss :  0.26713185077128204
Epoch $11/100 loss :  0.2511428925006286
Epoch $12/100 loss :  0.2316295734566191
Epoch $13/100 loss :  0.2383618484372678
Epoch $14/100 loss :  0.21599335774131442
Epoch $15/100 loss :  0.1955865955223208
Epoch $16/100 loss :  0.19238204476626022
Epoch $17/100 loss :  0.1788243819837985
Epoch $18/100 loss :  0.18463319280873175
Epoch $19/100 loss :  0.17786417253639386
Epoch $20/100 loss :  0.16760698997456094
Epoch $21/100 loss :  0.16630997006659923
Epoch $22/100 loss :  0.15308764981834785
Epoch $23/100 loss :  0.1458951821145804
Epoch $24/100 loss :  0.14978537951474605
Epoch $25/100 loss :  0.14429302173464195
Epoch $26/100 loss :  0.1377074234187603
Epoch $27/100 loss :  0.1348388165883396
Epoch $28/100 loss :  0.13717299311057382
Epoch $29/100 loss :  0.13118560320657233
Epoch $30/100 loss :  0.12429732408212579
Epoch $31/100 loss :  0.11706053578983182
Epoch $32/100 loss :  0.1194027420943198
Epoch $33/100 loss :  0.10964571069116177
Epoch $34/100 loss :  0.10691778669538705
Epoch $35/100 loss :  0.11131112504264583
Epoch $36/100 loss :  0.11016316809084105
Epoch $37/100 loss :  0.09803413956061653
Epoch $38/100 loss :  0.09919079773775909
Epoch $39/100 loss :  0.09552671582154605
Epoch $40/100 loss :  0.09940382101289603
Epoch $41/100 loss :  0.0876266185356223
Epoch $42/100 loss :  0.09290861322180084
Epoch $43/100 loss :  0.08687821897151678
Epoch $44/100 loss :  0.08794903771384903
Epoch $45/100 loss :  0.08116726188556007
Epoch $46/100 loss :  0.07999740127959977
Epoch $47/100 loss :  0.07533963352603756
Epoch $48/100 loss :  0.07815884831159012
Epoch $49/100 loss :  0.07562464726683886
Epoch $50/100 loss :  0.07679654115244099
Epoch $51/100 loss :  0.08081978438017161
Epoch $52/100 loss :  0.07765214914536994
Epoch $53/100 loss :  0.07050636183956395
Epoch $54/100 loss :  0.06610150246516518
Epoch $55/100 loss :  0.06449123277612355
Epoch $56/100 loss :  0.06395265504555858
Epoch $57/100 loss :  0.060744590611885425
Epoch $58/100 loss :  0.060048233069803406
Epoch $59/100 loss :  0.05872146643536246
Epoch $60/100 loss :  0.055535778605743595
Epoch $61/100 loss :  0.05672820568408655
Epoch $62/100 loss :  0.05395019520074129
Epoch $63/100 loss :  0.053738084378773754
Epoch $64/100 loss :  0.053788914709635406
Epoch $65/100 loss :  0.04899702733382583
Epoch $66/100 loss :  0.04860015897809163
Epoch $67/100 loss :  0.04860256324805643
Epoch $68/100 loss :  0.05289332208264133
Epoch $69/100 loss :  0.05502989341545364
Epoch $70/100 loss :  0.049363302633814186
Epoch $71/100 loss :  0.04705714296711528
Epoch $72/100 loss :  0.04970204030447032
Epoch $73/100 loss :  0.04964444282181237
Epoch $74/100 loss :  0.039865277181177036
Epoch $75/100 loss :  0.040363081325979336
Epoch $76/100 loss :  0.04065694167967076
Epoch $77/100 loss :  0.04062953117586996
Epoch $78/100 loss :  0.03888036594118761
Epoch $79/100 loss :  0.035249705203687365
Epoch $80/100 loss :  0.03540657161552783
Epoch $81/100 loss :  0.03311600224317416
Epoch $82/100 loss :  0.03717483068391195
Epoch $83/100 loss :  0.033095654788548534
Epoch $84/100 loss :  0.0330432604836381
Epoch $85/100 loss :  0.032475011251137956
Epoch $86/100 loss :  0.03201822503773576
Epoch $87/100 loss :  0.03325969727871859
Epoch $88/100 loss :  0.03663491334199258
Epoch $89/100 loss :  0.03899794401924895
Epoch $90/100 loss :  0.036115912639576454
Epoch $91/100 loss :  0.03614130903683279
Epoch $92/100 loss :  0.02570246996196068
Epoch $93/100 loss :  0.027507871040143073
Epoch $94/100 loss :  0.026861148096783007
Epoch $95/100 loss :  0.026752648409456015
Epoch $96/100 loss :  0.02721268009475392
Epoch $97/100 loss :  0.023717515575497047
Epoch $98/100 loss :  0.025126129753239777
Epoch $99/100 loss :  0.022923787640731618
Epoch $100/100 loss :  0.02108540137440128

In [19]:
#evaluation
model.eval()
total=0
correct=0

with torch.no_grad():
  for xb,yb in test_loader:
    outputs=model(xb)
    _,predicted=torch.max(outputs,1)

    correct+=(predicted==yb).sum().item()
    total+=yb.size(0) # actual samples in each batch

print("total samples : ",total)
print("correct samples : ",correct)

total samples :  180
correct samples :  170
Accuracy :  0.9444444444444444